### ISSUE TITLE
All **kwargs required

### ISSUE THREAD

**Issue by teresaejunior** [yglukhov/nimpy#196]
I spent some time trying to debug this in my code, and it can be boiled down to `foo_nim` demanding me to set the value for `c`:

tmp.nim:
```nim
import nimpy

proc foo_nim(a: int, b: int, c: int = 3, d: int = 4) {.exportpy.} =
  echo "Solution"
```

tmp2.py:
```py
from tmp import foo_nim

def foo_py(a, b, c=3, d=4):
    print('Success')
foo_py(1, b=2, d=4)

try:
    foo_nim(1, b=2, d=4)
except TypeError:
    print('Failed')

foo_nim(1, b=2, c=3, d=4)
```

    $ nim c -d:danger --passC:-march=native --app:lib -o:tmp.so tmp.nim 2>/dev/null && python3 tmp2.py
    Success
    Failed
    Solution

I have other issues, but I'm not sure if they are bugs or intended behaviour, and questions if you don't mind answering them:

1. In the example above, if I have `when isMainModule: foo_nim(1, b=2, d=4)` in tmp.nim, I get an extra "Solution" printed to the terminal. Which means I don't need to set `c` directly in Nim, but `isMainModule` seems to be ignored by nimpy. https://github.com/yglukhov/nimpy/issues/128 could be related. 
1. I can't receive proc arguments as `char`, I need to receive single character args as strings and convert them manually.
1. Nim `tables` objects are not returned as Python dictionaries, I have to return tuples.
1. My Nim module is a single function. Is there a performance hit from receiving a very large object thousands of times from Python (are they copied around every time)? Should I have a class instead that received the object once and a method that is called multiples times?

**Comment by yglukhov** [comment]
1. Yes, your main module is still "main" to nim. The correct question is "Should main module of a library define isMainModule as true?", which should be asked in nim circles.
2. With latest nimpy you should be able to receive `char` in nim, and pass `ord("a")` on the python side.
3. Tables must be marshalled to dicts iirc. Otherwise please report a proper issue with a sample.
4. Marshalling costs some performance of course, depending on type complexity. If that is critical you can use `PyObject` as an argument, and work with it like you would do in python.

**Comment by teresaejunior** [comment]
PyObject is great stuff. Thanks so much for your answers and help!
