### ISSUE TITLE
This code got compiled but not works

### ISSUE THREAD

**Issue by Serqati** [yglukhov/nimpy#214]
This code got compiled but not works

import nimpy
p = pyBuiltinsModule()
discard py.open("file.txt", "w").write("test")
 

(* file created but its empty )

**Comment by yglukhov** [comment]
Nim calling destructors at exit is a bit underdefined, so I suspect that the process just exists without flushing the file. Anyway you should never rely that your file will be closed automatically, that's why `with` statement exists in python.

In simpler words, just close the file after writing to it.

**Comment by Serqati** [comment]
Thanks ;) 

Can we use python decorators in nimpy?

**Comment by Serqati** [comment]
And with statement too ?

**Comment by yglukhov** [comment]
> Can we use python decorators in nimpy?

Yes and no, see #156

> And with statement too ?

One can easily implement that as a template.

P.S. Generally though it's not the best idea to call to python, when you can do the same natively in nim.

**Comment by Serqati** [comment]
Sorry
How to define python function with nimpy

**Comment by yglukhov** [comment]
Use exportpy pragma
```nim
proc foo(a: int) {.exportpy.} =
  echo a
```

**Comment by yglukhov** [comment]
Nice example of a with statement: https://github.com/yglukhov/nimpy/issues/240#issuecomment-982229058
