### ISSUE TITLE
numpy array integration [enhacement suggestion]

### ISSUE THREAD

**Issue by RUrlus** [yglukhov/nimpy#24]
Hi,

I recently discovered the package after failing to get pymod working with nim 18.0.
I am liking the simplicity of the nimpy but do find myself missing integration with Numpy arrays.

Is this something that you're planning on integrating?
I see a strong usecase for Nim in numerical computing / data science but integration with python/numpy is quite important.

I would be willing to help where I can but I am not very experienced in Nim yet.

Thank you for the work so far!

**Comment by yglukhov** [comment]
Hey @RUrlus, numpy was not on my radar tbh. I'm not familiar with numpy but from a 5 min intro I don't see any problems working with it via nimpy. Could you provide some samples/usecases of how you would like to interact with numpy?

**Comment by RUrlus** [comment]
Hi Yuriy,

Apologies for the late reply, the last week before my vacation was a bit hectic.
Thanks for the quick adaption. Is there something I can help with to finish it?

**Comment by RUrlus** [comment]
This might help as well [ndarray structure lecture](http://www.scipy-lectures.org/advanced/advanced_numpy/index.html#life-of-ndarray).

**Comment by LemonBoy** [comment]
Wrapping and unwrapping large chunks of memory from/to Python is quite easy using the [buffer protocol](https://docs.python.org/3/c-api/buffer.html), there's no need to call into the Numpy's C API.

The hard part is getting the memory ownership right since now there are two garbage collectors into play, right now I have some code that handles typed [MemoryView](https://docs.python.org/3/c-api/memoryview.html)s but as-is is very unsafe to use since it relies on the internal pointer not to be moved around.

**Comment by RUrlus** [comment]
@LemonBoy, thanks. I will have a look at the buffer protocol, although our take on easy might differ a bit:)
