### ISSUE TITLE
nim is slower than python

### ISSUE THREAD

**Issue by ablewolf** [yglukhov/nimpy#268]
The loop call is very difficult except for the parameters and the return value is int, even 10 times slower than python, I will post the test code later

**Comment by AndrewGPU** [comment]
proc testwdict(data: PyObject): int {.exportpy.} =
  for i in 0..100000:
    data["species"] = "哈哈哈"
  return 0

def testwdictsh(data):
    for i in range(0, 100001):
        data["species"] = "哈哈哈"
    return data

    print('Measuring python...')
    start_py = perf_counter()
    for i in range(0, 1000):
        testwdictsh({"name": "Banana", "species": "2", "age": 12})
    end_py = perf_counter()

    print('Measuring Nim...')
    start_nimt = perf_counter()
    for i in range(0, 1000):
        testwdict({"name": "Banana", "species": "2", "age": 12})
    end_nimt = perf_counter()

    print('---------')
    print('Python Elapsed: {:.2f}'.format(end_py - start_py))
    print('Nimt Elapsed: {:.2f}'.format(end_nimt - start_nimt))

**Comment by AndrewGPU** [comment]
result


Measuring python...
Measuring Nim...
---------
Python Elapsed: 4.09
Nimt Elapsed: 23.49

Except for simple math operations, even if you don't call pyobject, it will be slower than native Python, ...

**Comment by yglukhov** [comment]
What you're measuring here is marshalling overhead. Calling python from nim or nim from python involves marshalling, which takes time. Calling python from python, or nim from nim will always be faster. In this particular case I would guess the culprit is allocating python string `"哈哈哈"` in nim, while in python it is just a literal and no allocation happens.
