### ISSUE TITLE
Run time error when output shared library name does not match nim name.

### ISSUE THREAD

**Issue by flenniken** [yglukhov/nimpy#97]
You get a run time error when attempting to name a python shared library something other than the nim file name. The python module is built without error and the run time error isn't very helpful.

Create two files shown below, modname.nim and modname.py. Then create a python shared lib and run the python program.

```
$ cat modname.nim
import nimpy

proc hello*(): string {.exportpy.} =
  return "Hello"

$ nim c --hints:off --app:lib --out:hello.so modname

$ cat modname.py
import hello

print(hello.hello())

$ python modname.py

Traceback (most recent call last):
  File "modname.py", line 1, in <module>
    import hello
ImportError: dynamic module does not define init function
(inithello)
```

I would expect this example to run and print "Hello".  If it is not possible to support this, I would expect a compiler error message that tells that it is not supported and how to fix it.

Using nimpy version: 0.1.0-0e08b23 and nim version 0.19.4.

**Comment by yglukhov** [comment]
Unfortunately I don't see a way to do anything about it, and this behavior is documented (twice) in the README.

**Comment by flenniken** [comment]
I remember we talked about this before yet I keep making the same mistake. The behavior is contrary to my intuition.

I ran into the issue a few days ago when tracking down the two other problems I reported.  These all existed in my code and appeared when updating to the latest version of nimpy. It's misleading that there is no compiler error, yet it produces a non functioning library.

Is it possible to produce a compiler error or warning for this case?  If the code keeps track of the number of symbols exported per file, for zero symbols it would write a warning, for zero symbols and only one file, write an error?

**Comment by yglukhov** [comment]
Python expects the library to contain an init function which is named after the library. E.g. for `mymodule.so` library must contain `py_init_mymodule` (the name is not exact but you get the point) function. So technically it is possible to hit the same issue by just renaming an otherwise valid `so` file, and nimpy/nim is not related to this problem. We might somewhat tweak (i'm not saying "improve" here) the user experience if nim allowed to get output file name in compile time, but that's not the case, and even if it was, the benefits to me are rather illusory.
